Algoritmo "idades"

Var

 nome1 , nome2: caractere
 idade1 , idade2 : inteiro
 media: real
 


Inicio

escreval ("Dados da Primeira Pessoa: ")
escreva ("Nome: ")
leia (nome1)
escreva ("idade:")
leia (idade1)

escreval ("Dados da Segunda Pessoa: ")
escreva ("Nome2:")
leia (nome2)
escreva ("Idade2:")
leia (idade2)

media <- (idade1 + idade2) / 2

escreval("A idade media de ", nome1, " e ", nome2 , " eh de ", media , " anos ")




Fimalgoritmo